language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source financeager setup.py test
after_success:
  - coveralls
