language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt -e .
  - pip install coveralls
script:
  - coverage run --source financeager setup.py test
after_success:
  - coveralls
